import Link from 'next/link';
import Image from 'next/image';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-100">
      <div className="bg-white p-8 rounded-lg shadow-lg w-96">
        <h2 className="text-2xl font-bold mb-6 text-center">Welcome to My App</h2>
        <p className="text-center mb-6">
          Get started by editing 
        </p>
        <div className="flex justify-between">
          <Link href="/login" className="bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600">
            Login
          </Link>
          <Link href="/register" className="bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600">
            Register
          </Link>
        </div>
      </div>
      <div className="mt-8 text-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-500 hover:underline"
        >
          Powered by{' '}
          <Image
            src="/vercel.svg"
            alt="Vercel Logo"
            width={100}
            height={24}
            priority
          />
        </a>
      </div>
    </div>
  );
}
